### ISSUE TITLE
Merge statement, dealing with NULLs

### ISSUE THREAD

**Issue by visch** [storebrand/target-mssql#22]
The current merge statement condition https://github.com/storebrand/target-mssql/blob/main/target_mssql/sinks.py#L216 doesn't deal with NULLs. 

There is a way to do this with just boolean math, but I think the easiest way is to use `except`, I've been down this rabbit hole a few times if whoever is doing this has more questions!

**Comment by eivind-stb** [comment]
We've moved on from Meltano and are no longer maintaining this repository. Therefore I'm closing this issue.
