### ISSUE TITLE
Consider increasing Numeric spec to from 22,16 to 28,16

### ISSUE THREAD

**Issue by acarter24** [storebrand/target-mssql#27]
Using `https://github.com/voxmedia/tap-facebook-pages`, one schema declares the value field as number, it can contain reasonable sized decimals and some large integers (i.e. total video view time in seconds across 28 days).

I think the current `numeric` spec is `NUMERIC(22, 16))` leaving 8 digits to the left size of the point.

https://github.com/storebrand/target-mssql/blob/f043a2a1d43972500937eca18eade114b7a4b9bb/target_mssql/connector.py#L361

**Could this be increased to `NUMERIC(28, 16))`?**

From looking at the spec, it would seem to use up the same amount of memory as 22,16, so no impact there.

https://learn.microsoft.com/en-us/sql/t-sql/data-types/decimal-and-numeric-transact-sql?view=sql-server-ver16#arguments

I will do some testing in a fork to see if it resolves the issue.

**Comment by hholgersen** [comment]
You're absolutely right @acarter24, I made the same basic arithmetic mistake on target-oracle... Will fix so that the two match.

**Comment by acarter24** [comment]
I'm wrong also, 22-16 = SIX digits for the number :)

Thanks so much for the fix (in anticipation).

**Comment by hholgersen** [comment]
@acarter24 I got a new branch (almost) mimicking target-oracle behavior. Feel free to check out `numeric_types`. This has a new config, `prefer_float_over_numeric` that creates float column types instead of NUMBER so that precision doesn't have to be specified.

Like last time, it passes my tests but it would be great if you could give it a real try.

**Comment by hholgersen** [comment]
@acarter24 Sorry for the late reply, github doesn't notify me of new replies in issues. I have merged the PR and created a new release v0.2.0. Let me know when I can delete the branch.

**Comment by acarter24** [comment]
Please go ahead I'll repoint to the release. And thankyou :)
