### ISSUE TITLE
JSON Schema "multipleOf" validation error - numeric

### ISSUE THREAD

**Issue by AndrewLockton** [storebrand/target-mssql#31]
Getting the below error when trying to extract from a field that is of type numeric(11,7) in MSSQL

jsonschema.exceptions.ValidationError: 5.32 is not a multiple of 1e-07

**Comment by radbrt** [comment]
Hmmm... if you are able to get a hold of the raw singer records and schema that is being passed and causes the error, that would be very helpful. This kind of issue is new to me, so I will try to reproduce it.

**Comment by lumenn** [comment]
Hey, I'm diggin an old issue, but I'm facing same error in my case:

4578.68 is not multipleOf 1e-06

Any tips how could i retrieve that singer record and schema to update here? :)

**Comment by lumenn** [comment]
I've updated singer-sdk on my fork, and seems like it fixed the issue if anyone stumbles here ;)

**Comment by eivind-stb** [comment]
We've moved on from Meltano and are no longer maintaining this repository. Therefore I'm closing this issue.
